<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attendance Status Report(All)</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .table-wrapper {
          overflow-x: auto;
        }
        table tr th,table tr td{
          font-size: 13px;
        }
        .header-row {
            background-color: #f8f9fa;
        }

        th, td {
          font-size: 0.9rem;
        }
        .company-header {
          border-bottom: 2px solid #dee2e6;
        }
        .legend {
          font-size: 0.8rem;
        }
        @media print {
          body {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
          }

          @page {
            /* size: A4 landscape; */
            margin-top: 0;
          }
          
        }
    </style>
</head>
<body class="container-fluid py-4">
    <div class="company-header mb-4">
        <div class="row align-items-center">
            <div class="col-4">
                <h3 class="fw-bold" style="margin-top:-35px;position: absolute;">e.Gen Consultants Ltd</h3>
            </div>
            <div class="col-4">
                <h4 class="fw-bold text-center">Leave Report <br><p class="text-center h5">(Pending)</p></h4>
            </div>
            <div class="col-4 text-end">
                <img src="logo.png" alt="e.Gen Logo" height="60">
            </div>
        </div>
    </div>

    <div class="mb-3">
        <strong>Reporting Date: 2025-01-01 to 2025-01-31</strong><br>
        <strong>Report Generated Date:</strong> 05 Mar 2025, 10:17 am <br>
        <strong>Filter options: Type- replacement</strong>
    </div>

    <div class="table-wrapper">
        <table class="table table-bordered table-sm">
            <thead class="header-row">
                <tr class="text-center">
                    <th>SL.</th>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Designation</th>
                    <th>Leave Days</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                <tr class="text-center">
                    <td>1</td>
                    <td>11312312</td>
                    <td>Employee Name</td>
                    <td>Designation Name</td>
                    <td>1</td>
                    <td>1</td>
                </tr>
          
            </tbody>
        </table>
    </div>
    <hr>
    <div class="text-center">
      <small class="text-muted">Page 1 of 1</small>
    </div>
    <div class="text-end mt-3" style="position: absolute; right: 13px;
    margin-top: -20px !important;">
        <small class="text-muted">*This report is generated by <a href="https://mysoftheaven.com/">Mysoft Heaven (BD) Ltd</a></small><br>
        <small class="text-muted">*Provided by Mysoft Heaven (BD) Ltd</small>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>